import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {once} from 'node:events';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {chromium} from 'playwright';
import worker from '../../src/worker.mjs';
import {watchStore} from '../../src/lib/watch-store.mjs';
import {hashToken} from '../../src/lib/watch-auth.mjs';
import {WATCH_SOURCES} from '../../src/lib/watch-domain.mjs';

test('one job flow supports anonymous search, saved applications, connections and explicit daily alerts', {timeout:90000}, async()=>{
 const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');
 for(const file of readdirSync(new URL('../../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync(new URL('../../drizzle/'+file,import.meta.url),'utf8'));
 const db={prepare(query){return {bind(...values){return {
  async first(){return sql.prepare(query).get(...values)||null;},async all(){return {results:sql.prepare(query).all(...values)};},
  async run(){return {meta:{changes:Number(sql.prepare(query).run(...values).changes)}};},
 };}};},async batch(statements){sql.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}}};
 const store=watchStore(db),now=Date.now(),session='company-browser-test';
 const account=await store.saveAccount({id:'google:browser-company',email:'company@example.test',name:'Test User'},'test-hash',now);
 await store.createSession(await hashToken(session),account.id,now+3600000);
 await store.putValue('runnerHeartbeat',now);
 await store.preferences(account.id,{companies:['stripe'],roles:'platform',city:'Cork',level:'senior',arrangement:'any'});
 const source=WATCH_SOURCES.find(s=>s.id==='stripe');
 const seededJobs=Array.from({length:23},(_,i)=>({id:'stripe-'+i,providerId:String(i),sourceId:'stripe',source:'Stripe',company:'Stripe',title:i===0?'Junior Support Engineer':i===1?'Senior Platform Engineer':'Software Engineer '+i,location:'Dublin, Ireland · Hybrid',description:'Help customers build and troubleshoot their integrations. Collaborate with engineers and improve our support tools. JavaScript, APIs and communication skills.',url:'https://stripe.com/test-job/'+i,salary:'',remote:false}));
 await store.claimSource('stripe','seed',now,0);
 await store.saveSnapshot(source,'seed',{kind:'success',complete:true,skipped:0,jobs:seededJobs},now);
 const originalFetch=globalThis.fetch;
 globalThis.fetch=async input=>{
  const url=new URL(input);
  if(url.hostname==='cloudflare-dns.com')return Response.json({Status:0,Answer:url.searchParams.get('type')==='A'?[{type:1,data:'93.184.216.34'}]:[]});
  if(url.hostname==='careers.acme.com')return new Response('<a href="https://jobs.ashbyhq.com/browser-demo">Open jobs</a>',{headers:{'Content-Type':'text/html'}});
  if(url.hostname==='blocked.acme.com')return new Response('Forbidden',{status:403});
  if(url.hostname==='example.org')return new Response('<h1>Careers</h1>',{headers:{'Content-Type':'text/html'}});
  if(url.hostname==='api.smartrecruiters.com')return Response.json({totalFound:1,content:[{id:'744000150116754',name:'Senior Support Engineer',company:{identifier:'LinkedIn3'},visibility:'PUBLIC',location:{city:'Dublin',country:'ie',hybrid:true}}]});
  if(url.hostname==='api.ashbyhq.com')return Response.json({jobs:[{title:'Support Engineer',location:'Dublin, Ireland',jobUrl:'https://jobs.ashbyhq.com/browser-demo/11111111-2222-3333-4444-555555555555',descriptionPlain:'Help customers use the software.',isListed:true}]});
  if(url.hostname==='api.lever.co')return Response.json([{id:'22222222-2222-3333-4444-555555555555',text:'Support Specialist',categories:{location:'Dublin, Ireland'},hostedUrl:'https://jobs.lever.co/browser-other/22222222-2222-3333-4444-555555555555',descriptionPlain:'Help customers use the software.'}]);
  if(url.hostname==='boards-api.greenhouse.io'||url.hostname==='remotive.com')return Response.json({jobs:[]});
  return new Response('Unavailable in this isolated test',{status:503});
 };
 let origin,browser;const failures=[];
 const server=createServer(async(req,res)=>{
  try{
   const chunks=[];for await(const chunk of req)chunks.push(chunk);
   const response=await worker.fetch(new Request(new URL(req.url,origin),{method:req.method,headers:req.headers,...(chunks.length?{body:Buffer.concat(chunks)}:{})}),{
    DB:db,GOOGLE_CLIENT_ID:'test.apps.googleusercontent.com',WATCH_RUNNER_SECRET:'test-only-secret',ALERTS_ENABLED:'true',
    ASSETS:{fetch:async request=>{
     const path=new URL(request.url).pathname;const ext=path.split('.').at(-1);
     const types={js:'text/javascript',css:'text/css',html:'text/html',svg:'image/svg+xml',png:'image/png',woff2:'font/woff2'};
     try{return new Response(readFileSync(new URL('../../dist/client'+(path==='/'?'/index.html':path),import.meta.url)),{headers:{'Content-Type':types[ext]||(path==='/'?'text/html':'application/octet-stream')}});}catch{return new Response('Not found',{status:404});}
    }},
   });
   res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));
  }catch(e){failures.push(e.message);res.writeHead(500);res.end('Test failed');}
 });
 try{
  server.listen(0,'127.0.0.1');await once(server,'listening');origin=`http://127.0.0.1:${server.address().port}`;
  browser=await chromium.launch({headless:true,channel:process.env.JOBPILOT_TEST_BROWSER_CHANNEL||'chrome'});
  const context=await browser.newContext({viewport:{width:1440,height:1000}});
  const page=await context.newPage();page.on('pageerror',error=>failures.push(error.message));
  await page.goto(origin+'/#watch');
  await page.locator('.job-result-row').first().waitFor();
  assert.equal(await page.locator('.new-job-badge').count(),0);
  sql.prepare('UPDATE watch_vacancies SET first_seen=?').run(now-7200000);
  sql.prepare('UPDATE watch_vacancies SET first_seen=? WHERE id=?').run(now,'stripe-0');
  await page.evaluate(value=>localStorage.setItem('jobpilot.visit.v1',JSON.stringify(value)),{since:now-7200000,lastSeen:now-3600000});
  await page.reload();
  await page.getByRole('button',{name:'New since last visit (1)',exact:true}).waitFor();
  await page.locator('#watch-new-toggle').click();
  await page.locator('#watch-result-count').filter({hasText:'1 job new since last visit'}).waitFor();
  assert.equal(await page.locator('.job-result-row').count(),1);
  await page.reload();
  await page.getByRole('button',{name:'New since last visit (1)',exact:true}).waitFor();
  assert.equal(await page.locator('.new-job-badge').count(),1);
  assert.equal(await page.locator('nav[aria-label="Main sections"] button').count(),3);
  assert.equal(await page.locator('.job-result-row').count(),20);
  assert.match(await page.locator('#watch-result-count').innerText(),/23 jobs/);
  assert.equal(await page.locator('#watch-more').isVisible(),true);
  const firstRow=await page.locator('.job-result-row').first().boundingBox();
  assert.ok(firstRow.y+firstRow.height<page.viewportSize().height, 'The first desktop job must be fully visible beside the filters without scrolling');
  assert.ok((await page.locator('.search-rail').boundingBox()).x<(await page.locator('.search-content').boundingBox()).x);
  await page.locator('.job-result-row').first().evaluate(async el=>{await Promise.all(el.parentElement.getAnimations({subtree:true}).map(a=>a.finished));});
  await page.screenshot({path:'/private/tmp/jobpilot-refined-desktop.png',fullPage:false});
  await page.locator('#watch-more').click();assert.equal(await page.locator('.job-result-row').count(),23);
  await page.locator('#watch-company-open').click();
  await page.locator('#watch-company-filter').fill('Stripe');
  await page.locator('[data-watch-company="stripe"]').check();
  await page.locator('#watch-companies').getByText('23 Ireland / eligible remote jobs',{exact:false}).waitFor();
  await page.locator('#company-dialog').getByRole('button',{name:'Show jobs',exact:true}).click();
  await page.locator('#watch-roles').fill('support');await page.locator('#watch-city').fill('Dublin');
  await page.locator('#watch-more-filters summary').click();
  await page.locator('#watch-level').selectOption('entry');await page.locator('#watch-arrangement').selectOption('hybrid');
  await page.locator('#watch-search').click();
  await page.locator('#watch-result-count').filter({hasText:'1 job to explore'}).waitFor();
  assert.match(await page.locator('[data-match-group="experience_unclear"]').innerText(),/experience unclear/);
  await page.locator('#watch-sponsorship').selectOption('needed');
  await page.locator('#watch-includeInternships').check();
  await page.locator('#watch-includeApprenticeships').check();
  await page.locator('#watch-search').click();
  const role=page.locator('.job-result-row');
  await role.getByRole('button',{name:'Junior Support Engineer',exact:true}).click();
  assert.equal(await page.locator('#job-dialog').isVisible(),true);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#job-dialog').isVisible(),false);
  assert.equal(await role.getByRole('button',{name:'Junior Support Engineer',exact:true}).evaluate(el=>el===document.activeElement),true);
  await role.locator('[data-watch-save]').click();
  await role.getByRole('button',{name:'Saved Junior Support Engineer',exact:true}).waitFor();
  await page.locator('.flying-save').waitFor({state:'visible'});
  await page.locator('.flying-save').waitFor({state:'detached'});
  await context.route('https://stripe.com/test-job/*',route=>route.fulfill({body:'Employer application form'}));
  const popupWait=page.waitForEvent('popup');await role.locator('.apply-job').click();const popup=await popupWait;
  await popup.waitForLoadState();assert.equal(popup.url(),'https://stripe.com/test-job/0');await popup.close();
  await page.getByRole('button',{name:'My applications',exact:false}).click();
  assert.match(await page.locator('#full-queue').innerText(),/Saved/);
  assert.doesNotMatch(await page.locator('#full-queue').innerText(),/Applied/);
  await page.locator('nav[aria-label="Main sections"] [data-nav="watch"]').click();
  await page.locator('#watch-result-count').filter({hasText:'1 job to explore'}).waitFor();
  await page.locator('#watch-alert-open').click();
  assert.match(await page.locator('#watch-alert-summary').innerText(),/support/);
  assert.equal(await page.locator('#watch-subscription-actions').isVisible(),false);
  // Stub Google's identity provider only; preferences, consent and account state use the real worker + SQLite.
  await page.evaluate(()=>{let callback;window.google={accounts:{id:{initialize(options){callback=options.callback;},renderButton(element){const b=document.createElement('button');b.textContent='Google test account';b.onclick=()=>callback({credential:'isolated-test-credential'});element.replaceChildren(b);}}}};});
  await page.route('**/watch-api/google',async route=>{await context.addCookies([{name:'jp_watch_session',value:session,url:origin}]);await route.fulfill({json:{ok:true}});});
  await page.locator('#watch-signin').click();await page.getByRole('button',{name:'Google test account',exact:true}).click();
  await page.locator('#watch-subscription-actions').waitFor();
  assert.match(await page.locator('#watch-alert-summary').innerText(),/support/);
  assert.doesNotMatch(await page.locator('#watch-alert-summary').innerText(),/platform|Cork/);
  assert.equal((await store.account(account.id)).status,'inactive');
  await page.locator('#watch-subscribe').click();
  assert.match(await page.locator('#watch-flow-error').innerText(),/choose to receive daily emails/);
  assert.equal((await store.account(account.id)).status,'inactive');
  await page.locator('#watch-email-consent').check();await page.locator('#watch-subscribe').click();
  await page.locator('#watch-alert-success').waitFor();
  const subscribed=await store.account(account.id);assert.equal(subscribed.status,'active');
  assert.deepEqual(subscribed.preferences,{companies:['stripe'],roles:'support',city:'Dublin',level:'entry',arrangement:'hybrid',sponsorship:'needed',includeInternships:true,includeApprenticeships:true});
  await page.screenshot({path:'/private/tmp/jobpilot-redesign-success.png'});
  const savedAlertSearch={...subscribed.preferences,companies:['amazon','mastercard','stripe']};
  await store.preferences(account.id,savedAlertSearch);
  await page.getByRole('button',{name:'Back to jobs',exact:true}).click();
  const reloadSearch=page.waitForResponse(r=>r.url().endsWith('/watch-api/jobs'));
  await page.reload();await reloadSearch;
  await page.locator('#watch-results[aria-busy="false"]').waitFor();
  assert.equal(await page.locator('[data-watch-company]:checked').count(),0,'Reload must not restore the saved alert companies');
  assert.equal(await page.locator('#watch-selected-count').innerText(),'All companies');
  await page.locator('#watch-result-count').filter({hasText:'23 jobs'}).waitFor();
  assert.equal(await page.locator('.save-job.is-saved').count(),1);
  assert.equal(await page.locator('#watch-roles').inputValue(),'');
  assert.equal(await page.locator('#watch-city').inputValue(),'');
  assert.equal(await page.locator('#watch-level').inputValue(),'any');
  assert.equal(await page.locator('#watch-arrangement').inputValue(),'any');
  assert.equal(await page.locator('#watch-sponsorship').inputValue(),'any');
  assert.equal(await page.locator('#watch-includeInternships').isChecked(),false);
  assert.equal(await page.locator('#watch-includeApprenticeships').isChecked(),false);
  assert.deepEqual((await store.account(account.id)).preferences,savedAlertSearch);
  const companyNames=await page.locator('.company-choice-name strong').allTextContents();
  assert.deepEqual(companyNames,[...companyNames].sort((a,b)=>a.localeCompare(b,'en',{sensitivity:'base',numeric:true})));
  await page.locator('#watch-alert-open').click();await page.locator('#watch-load-saved').click();
  await page.locator('#watch-result-count').filter({hasText:'1 job to explore'}).waitFor();
  assert.equal(await page.locator('[data-watch-company]:checked').count(),3,'Saved searches still load when explicitly requested');
  assert.equal(await page.locator('#watch-roles').inputValue(),'support');
  await page.locator('#watch-pause').click();
  await page.locator('#watch-account-state').filter({hasText:'Daily alerts paused'}).waitFor();
  assert.equal(await page.locator('#watch-subscribe').isEnabled(),true);
  await page.locator('[data-close-dialog="alert-dialog"]').first().click();
  await page.locator('#watch-reset').click();
  await page.locator('#watch-company-open').click();await page.locator('#watch-company-filter').fill('Browser Example');
  await page.locator('#watch-add-company').click();
  await page.locator('#watch-request-form [name=url]').fill('https://careers.acme.com/jobs');
  await page.getByRole('button',{name:'Check and connect',exact:true}).click();
  await page.locator('#watch-request-message').filter({hasText:'is connected and selected'}).waitFor();
  assert.equal((await store.sources()).filter(s=>s.id==='ashby-browser-demo').length,1);
  await page.locator('#watch-company-filter').fill('Browser Example');
  assert.equal(await page.locator('[data-watch-company="ashby-browser-demo"]').isChecked(),true);
  await page.locator('#watch-request-form [name=name]').fill('Unsupported');
  await page.locator('#watch-request-form [name=url]').fill('https://example.org/careers');
  await page.getByRole('button',{name:'Check and connect',exact:true}).click();
  await page.locator('#watch-request-message').filter({hasText:'No supported public job board was found'}).waitFor();
  assert.ok(!(await store.sources()).some(s=>s.name==='Unsupported'));
  assert.match(await page.locator('#watch-companies').innerText(),/Unsupported/);
  assert.match(await page.locator('#watch-companies').innerText(),/Saved link · Connection needs attention/);
  assert.match(await page.locator('#watch-request-message').innerText(),/Greenhouse, Lever, Ashby, Workday or SmartRecruiters/);
  assert.doesNotMatch(await page.locator('#watch-companies').innerText(),/not checked yet/);
  await page.locator('#watch-companies').getByRole('button',{name:'Retry connection',exact:true}).click();
  await page.locator('#watch-request-message').filter({hasText:'No supported public job board was found'}).waitFor();
  await page.locator('#watch-request-form [name=name]').fill('Blocked Example');
  await page.locator('#watch-request-form [name=url]').fill('https://blocked.acme.com/careers');
  await page.getByRole('button',{name:'Check and connect',exact:true}).click();
  await page.locator('#watch-companies .connection-reason').filter({hasText:'limits automated requests'}).waitFor();
  await page.reload();await page.locator('.job-result-row').first().waitFor();
  await page.locator('#watch-company-open').click();await page.locator('#watch-company-filter').fill('Blocked Example');
  const blockedRow=page.locator('#watch-companies .company-link');
  assert.match(await blockedRow.locator('.connection-reason').innerText(),/limits automated requests/);
  assert.match(await blockedRow.locator('.connection-checked').innerText(),/Last connection attempt/);
  await blockedRow.getByRole('button',{name:'Change link',exact:true}).click();
  assert.equal(await page.locator('#watch-request-form [name=url]').inputValue(),'https://blocked.acme.com/careers');
  assert.equal(await page.getByRole('button',{name:'Check and connect',exact:true}).isEnabled(),true);
  await page.locator('#watch-request-form [name=name]').fill('LinkedIn');
  await page.locator('#watch-request-form [name=url]').fill('https://www.linkedin.com/jobs/search/');
  await page.getByRole('button',{name:'Check and connect',exact:true}).click();
  await page.locator('#watch-request-message').filter({hasText:'LinkedIn job-search'}).waitFor();
  const linkedIn=page.locator('#watch-companies .company-link').filter({has:page.getByText('LinkedIn',{exact:true})});
  await linkedIn.waitFor({state:'visible'});
  assert.match(await linkedIn.innerText(),/Saved link · Connection needs attention/);
  assert.equal(await linkedIn.locator('input[type=checkbox]').count(),0,'Saved links must not pretend to filter synced jobs');
  await linkedIn.locator('summary').click();
  assert.match(await linkedIn.innerText(),/employer’s own/);
  await context.route('https://www.linkedin.com/jobs/search/',route=>route.fulfill({body:'LinkedIn jobs page'}));
  const careersPageWait=page.waitForEvent('popup');
  await linkedIn.getByRole('link',{name:'Open careers page',exact:false}).click();
  const careersPage=await careersPageWait;await careersPage.waitForLoadState();
  assert.equal(careersPage.url(),'https://www.linkedin.com/jobs/search/');await careersPage.close();
  assert.equal((await store.sources()).some(s=>s.home==='https://www.linkedin.com/jobs/search/'),false);
  await page.locator('#watch-company-filter').fill('');
  const namesAfterAdding=await page.locator('.company-choice-name strong').allTextContents();
  assert.ok(namesAfterAdding.includes('LinkedIn')&&namesAfterAdding.includes('Unsupported')&&namesAfterAdding.includes('Browser Example'));
  assert.deepEqual(namesAfterAdding,[...namesAfterAdding].sort((a,b)=>a.localeCompare(b,'en',{sensitivity:'base',numeric:true})));
  await page.screenshot({path:'/private/tmp/jobpilot-redesign-companies.png'});
  await page.locator('#company-dialog').getByRole('button',{name:'Show jobs',exact:true}).click();
  await page.locator('#watch-reset').click();
  await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});
  assert.equal(await page.locator('#search-filter-panel').getAttribute('open'),null);
  await page.locator('#watch-result-count').filter({hasText:'24 jobs'}).waitFor();
  await page.locator('#toast').evaluate(el=>el.classList.remove('visible','is-visible'));
  await page.screenshot({path:'/private/tmp/jobpilot-refined-mobile.png'});
  const mobileRow=await page.locator('.job-result-row').first().boundingBox();
  assert.ok(mobileRow.y+mobileRow.height<page.viewportSize().height-64,'The first mobile role remains fully visible above the navigation');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  assert.equal(await page.locator('.job-result-row').first().evaluate(el=>getComputedStyle(el).animationName),'none');
  await page.locator('.mobile-dock [data-nav="tailor"]').click();
  assert.equal(await page.locator('#tailor-title').isVisible(),true);
  await page.locator('.mobile-dock [data-nav="watch"]').click();
  assert.equal(await page.locator('.mobile-dock [data-nav="watch"]').getAttribute('aria-current'),'page');
  await page.locator('#watch-alert-open').click();
  await page.locator('#watch-alert-edit').click();
  await page.locator('#alert-dialog').waitFor({state:'hidden'});
  assert.equal(await page.locator('#search-filter-panel').evaluate(el=>el.open),true);
  assert.equal(await page.evaluate(()=>document.activeElement.id),'watch-roles','Edit search should focus the expanded filters');
  await page.locator('#watch-company-open').click();
  assert.equal(await page.locator('#company-dialog').evaluate(el=>el.scrollWidth<=el.clientWidth),true);
  await page.locator('#watch-company-filter').fill('linkedin');
  await linkedIn.waitFor({state:'visible'});
  assert.equal(await linkedIn.getByRole('link',{name:'Open careers page',exact:false}).isVisible(),true);
  await page.screenshot({path:'/private/tmp/jobpilot-companies-mobile.png'});
  // Native search fields consume the first Escape to clear their current query.
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#watch-company-filter').inputValue(),'');
  await page.keyboard.press('Escape');
  await page.locator('#company-dialog').waitFor({state:'hidden'});
  await page.locator('#search-filter-panel > summary').click();
  await page.locator('.job-title-button').first().click();
  await page.screenshot({path:'/private/tmp/jobpilot-refined-mobile-details.png'});
  assert.ok((await page.locator('#job-dialog').boundingBox()).y>0);
  assert.equal((await page.locator('#job-dialog').boundingBox()).width,390,'Mobile job details should fill the screen width');
  assert.equal(await page.locator('#job-dialog').evaluate(el=>el.scrollWidth<=el.clientWidth),true);
  await page.keyboard.press('Escape');
  for(const width of [720,1024,1280]){
    await page.setViewportSize({width,height:900});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`No horizontal overflow at ${width}px`);
  }
  for(const width of [1440,390]){
    await page.setViewportSize({width,height:1000});
    if(width===390)await page.locator('#search-filter-panel > summary').click();
    await page.locator('#watch-roles').fill('platform');await page.locator('#watch-city').fill('Cork');
    await page.locator('#watch-more-filters summary').click();
    await page.locator('#watch-level').selectOption('senior');await page.locator('#watch-arrangement').selectOption('remote');
    await page.locator('#watch-company-open').click();await page.locator('[data-watch-company="stripe"]').check();
    await page.locator('#company-dialog').getByRole('button',{name:'Show jobs',exact:true}).click();
    await page.locator(width===390?'.mobile-dock [data-nav="queue"]':'nav[aria-label="Main sections"] [data-nav="queue"]').click();
    const navigation=page.waitForEvent('domcontentloaded',{timeout:5000});
    await page.locator(width===390?'.mobile-brand':'.brand').click();await navigation;
    await page.locator('#watch-result-count').filter({hasText:'24 jobs'}).waitFor();
    assert.equal(new URL(page.url()).hash,'');
    assert.equal(await page.locator('#watch-selected-count').textContent(),'All companies');
    assert.equal(await page.locator('[data-watch-company]:checked').count(),0);
    assert.equal(await page.locator('#watch-roles').inputValue(),'');assert.equal(await page.locator('#watch-city').inputValue(),'');
    assert.equal(await page.locator('#watch-level').inputValue(),'any');assert.equal(await page.locator('#watch-arrangement').inputValue(),'any');
    assert.equal(await page.locator('#watch-company-filter').inputValue(),'');
    assert.equal(await page.locator('.save-job.is-saved').count(),1,'Logo refresh keeps saved applications');
    assert.deepEqual((await store.account(account.id)).preferences,savedAlertSearch,'Logo refresh keeps email alert settings');
    const refreshedCompanies=await page.locator('.company-choice-name strong').allTextContents();
    assert.ok(refreshedCompanies.includes('LinkedIn')&&refreshedCompanies.includes('Unsupported'),'Saved careers links stay in the company list after reload');
  }
  // Connecting LinkedIn's own careers page activates the employer feed, independently of a saved job-search link.
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('#watch-company-open').click();
  await page.locator('#watch-company-filter').fill('LinkedIn careers');
  await page.locator('#watch-add-company').click();
  await page.locator('#watch-request-form [name=url]').fill('https://careers.linkedin.com/');
  await page.getByRole('button',{name:'Check and connect',exact:true}).click();
  await page.locator('#watch-request-message').filter({hasText:'is connected and selected'}).waitFor();
  assert.equal(await page.locator('[data-watch-company="linkedin"]').isChecked(),true);
  assert.equal((await store.catalog(Date.now())).find(s=>s.id==='linkedin').count,1);
  await page.screenshot({path:'/private/tmp/jobpilot-linkedin-connected.png'});
  await page.locator('#company-dialog').getByRole('button',{name:'Show jobs',exact:true}).click();
  await page.locator('#watch-result-count').filter({hasText:'1 job'}).waitFor();
  assert.match(await page.locator('.job-result-row').innerText(),/Senior Support Engineer/);
  assert.deepEqual(failures,[]);
 }finally{globalThis.fetch=originalFetch;await browser?.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));sql.close();}
});
