import {fillApplication} from '/extension/automation.js';
import {inspectSubmission} from '/extension/submission.js';
const $=selector=>document.querySelector(selector);let clicks=0;$('#submit').addEventListener('click',()=>clicks++);
$('#run').addEventListener('click',()=>{
 const results=[];const check=(label,value)=>results.push(`${value?'PASS':'FAIL'}: ${label}`);
 const expectedUrl=location.href;const profile={name:'Test Middle Candidate',firstName:'Test Middle',lastName:'Candidate',email:'test@example.org',location:'Dublin',summary:'My approved short introduction.'};
 const initial=inspectSubmission({expectedUrl});check('Recognises Ashby with a sibling submit button outside the field container',initial.formKind==='ashby'&&!$('.ashby-application-form-container').contains($('#submit')));
 check('Empty fields cannot be submitted',!initial.ready);
 check('Autofill without a selected form is blocked',fillApplication({profile}).blocked===true);
 const report=fillApplication({profile,resume:{name:'fixture.pdf',base64:btoa('%PDF-test')},formKind:initial.formKind,expectedUrl});
 check('Full name and email fill correctly',$('#name').value===profile.name&&$('#email').value===profile.email);
 check('Saved short introduction fills the custom prompt',$('#intro').value===profile.summary);
 check('Location suggestion is left for the applicant',$('[role=combobox]').value===''&&report.untouched.some(x=>x.includes('Where are you located')));
 check('Newsletter remains empty',$('[name=newsletter_email]').value==='');
 check('Generic resume-autofill upload is untouched',$('#generic-upload').files.length===0);
 check('Resume attached to the intended field',$('#resume').files[0]?.name==='fixture.pdf');
 check('Upload must complete before submission',inspectSubmission({expectedUrl}).blockers.some(x=>x.includes('upload to finish')));
 const entry=$('[data-field-path="_systemfield_resume"]');const file=document.createElement('p');file.className='ashby-application-form-input-file-item-name';file.textContent='fixture.pdf';entry.append(file);const remove=document.createElement('button');remove.className='ashby-application-form-input-file-item-delete';remove.textContent='Delete file';entry.append(remove);$('#resume').value='';
 check('Completed provider upload satisfies required resume after file input clears',!inspectSubmission({expectedUrl}).blockers.some(x=>/^Resume/.test(x)));
 $('[role=combobox]').value='Dublin, County Dublin, Ireland';
 check('Location still requires explicit applicant review',!inspectSubmission({expectedUrl}).ready);
 check('Reviewed completed form is ready',inspectSubmission({expectedUrl,customAnswersReviewed:true}).ready);
 $('[role=combobox]').setAttribute('aria-expanded','true');check('Open suggestion menu pauses submission',!inspectSubmission({expectedUrl,customAnswersReviewed:true}).ready);$('[role=combobox]').setAttribute('aria-expanded','false');
 const custom=document.createElement('input');custom.setAttribute('role','combobox');custom.setAttribute('aria-required','true');custom.value='Unverified';$('.ashby-application-form-container').append(custom);check('Unknown required custom controls remain blocked',!inspectSubmission({expectedUrl,customAnswersReviewed:true}).ready);custom.remove();
 const error=document.createElement('p');error.setAttribute('role','alert');error.textContent='Upload failed';entry.append(error);check('Employer validation errors block submission',!inspectSubmission({expectedUrl,customAnswersReviewed:true}).ready);error.remove();
 const second=fillApplication({profile:{...profile,email:'different@example.org'},resume:{name:'new.pdf',base64:btoa('%PDF-test')},formKind:'ashby',expectedUrl});check('Second fill preserves both answers and completed upload',second.filled.length===0&&$('#email').value===profile.email);
 const submit=$('#submit'),panel=$('#application-panel');
 document.body.append(submit);check('Submit buttons outside the application panel are not used',!inspectSubmission({expectedUrl,customAnswersReviewed:true}).ready);panel.append(submit);
 const extra=document.createElement('div');extra.className='ashby-application-form-container';panel.append(extra);check('A shared panel with multiple field containers is blocked',!inspectSubmission({expectedUrl,customAnswersReviewed:true}).ready);extra.remove();
 const terms=document.createElement('p');terms.textContent='By submitting you agree to our terms.';panel.append(terms);check('Agreement beside the field container still blocks submission',!inspectSubmission({expectedUrl,customAnswersReviewed:true}).ready);terms.remove();
 const panelError=document.createElement('p');panelError.setAttribute('role','alert');panelError.textContent='Application could not be validated.';panel.append(panelError);check('Validation errors beside the fields block submission',!inspectSubmission({expectedUrl,customAnswersReviewed:true}).ready);panelError.remove();
 check('No implicit submission occurs',clicks===0);
 const submitted=inspectSubmission({expectedUrl,customAnswersReviewed:true,commit:true});check('Explicit local test commit clicks exactly once',submitted.clicked&&clicks===1);
 $('#results').textContent=results.join('\n');
});
