import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { prepareApplication, canonicalUrl, publicUrl, structuredJob, validateProfile } from '../lib/domain.mjs';
import { importJob, isPublicAddress } from '../lib/importer.mjs';
import { openStore } from '../lib/store.mjs';
import { createApp } from '../server.mjs';

const profile = validateProfile({ name:'Test Candidate', email:'candidate@jobpilot.test', skills:'React, HTML, CSS', resumeText:'I develop web applications with React and JavaScript. My experience includes testing, troubleshooting, and documentation for customer support teams.' });
const job = { title:'Frontend Developer', company:'Example Employer', url:'https://example.org/careers/123', location:'Dublin', salary:'', description:'Build accessible products with React, JavaScript, CSS, TypeScript and Docker. Work with the team on testing, documentation, and application troubleshooting.',notes:'',followUp:'' };
async function withStore(run) { const directory=await mkdtemp(path.join(os.tmpdir(),'jobpilot-test-')); const store=await openStore(directory);try{await run(store,directory);}finally{store.close();await rm(directory,{recursive:true,force:true});} }

test('matching reflects actual résumé evidence and identifies missing skills',()=>{const result=prepareApplication(profile,job);assert(result.matched.includes('React'));assert(result.missing.includes('TypeScript'));assert(result.missing.includes('Docker'));assert(!result.opening.includes('Docker'));assert.equal(result.coverage,Math.round(100*result.matched.length/result.mentioned.length));assert.equal(prepareApplication(profile,{...job,description:'Seeking a diligent colleague.'}).coverage,null);});
test('preparation detects missing profile requirements',()=>{const result=prepareApplication(validateProfile({}),job);assert(result.blockers.some(item=>item.includes('email')));assert(result.blockers.some(item=>item.includes('résumé')));});
test('canonical URLs remove tracking and application suffixes without losing job identity',()=>{assert.equal(canonicalUrl('https://jobs.lever.co/team/123/apply?utm_source=foo'),canonicalUrl('https://jobs.lever.co/team/123'));assert.equal(canonicalUrl('https://ie.indeed.com/viewjob?jk=abc&from=search'),canonicalUrl('https://www.indeed.com/viewjob?vjk=abc'));assert.notEqual(canonicalUrl('https://example.org/job?id=1'),canonicalUrl('https://example.org/job?id=2'));});
test('unsafe link schemes and private import targets are rejected',()=>{for(const url of ['javascript:alert(1)','https://user:pass@example.org','http://localhost/job','https://example.org:444/job'])assert.throws(()=>publicUrl(url));for(const address of ['127.0.0.1','10.1.1.1','169.254.169.254','100.64.0.1','::1','::ffff:127.0.0.1','fe80::1','2002:7f00:1::'])assert.equal(isPublicAddress(address),false);assert.equal(isPublicAddress('8.8.8.8'),true);});
test('JSON-LD imports graph postings and strips markup',()=>{const html='<script type="application/ld+json">'+JSON.stringify({'@graph':[{'@type':'Organization'},{'@type':'JobPosting',title:'UI Engineer',hiringOrganization:{name:'Example'},description:'<p>React &amp; CSS</p>',jobLocation:{address:{addressLocality:'Dublin',addressCountry:'IE'}}}]})+'</script>';const result=structuredJob(html,job.url);assert.equal(result.company,'Example');assert.equal(result.description,'React & CSS');assert.equal(result.location,'Dublin, IE');assert.throws(()=>structuredJob('<html>No job here</html>',job.url),/does not expose/);});
test('Greenhouse and Lever imports use public job endpoints',async()=>{let endpoint;const greenhouse=await importJob('https://job-boards.greenhouse.io/example/jobs/123',async url=>{endpoint=url;return JSON.stringify({title:'Engineer',company_name:'Example',content:'React and CSS',location:{name:'Dublin'}});});assert.match(endpoint,/boards-api.greenhouse.io/);assert.equal(greenhouse.company,'Example');const lever=await importJob('https://jobs.lever.co/example/12345678-abcd-1234-abcd-123456789abc',async()=>JSON.stringify({text:'Support Specialist',descriptionPlain:'Customer support',categories:{location:'Remote'},lists:[{text:'Requirements',content:'<li>SaaS</li>'}]}));assert.match(lever.description,/SaaS/);assert.equal(lever.location,'Remote');});
test('store persists, rejects duplicate roles, and preserves drafts when notes change',()=>withStore(async(store,directory)=>{store.saveProfile(profile);store.putResume('resume.pdf',Buffer.from('%PDF-test'),profile.resumeText);const saved=store.add(job);assert.throws(()=>store.add({...job,url:job.url+'?utm_source=another'}),/already/);store.prepare(saved.id);store.update(saved.id,{notes:'Follow up next week',followUp:'2026-10-01'});assert.equal(store.getJob(saved.id).status,'prepared');assert(store.getJob(saved.id).preparation.opening);const other=await openStore(directory);assert.equal(other.jobs().length,1);other.close();}));
test('application evidence is required and recorded submissions cannot be reset',()=>withStore(async store=>{const saved=store.add(job);assert.throws(()=>store.changeStatus(saved.id,{status:'submitted'}));store.changeStatus(saved.id,{status:'submitted',evidence:{note:'Received application confirmation email, reference ABC123.'}});assert(store.getJob(saved.id).evidence);assert.throws(()=>store.changeStatus(saved.id,{status:'saved'}),/cannot be reset/);assert.throws(()=>store.prepare(saved.id),/already recorded/);store.changeStatus(saved.id,{status:'interview'});assert.equal(store.getJob(saved.id).status,'interview');}));
test('backups round-trip drafts, resume and evidence; bad restore leaves current data intact',()=>withStore(async store=>{store.saveProfile(profile);store.putResume('resume.pdf',Buffer.from('%PDF-test'),profile.resumeText);const saved=store.add(job);store.prepare(saved.id);const snapshot=store.snapshot();await store.restore(snapshot);assert.equal(store.getJob(saved.id).preparation.opening,snapshot.jobs[0].preparation.opening);assert.equal(store.resume().name,'resume.pdf');await assert.rejects(store.restore({...snapshot,jobs:[snapshot.jobs[0],snapshot.jobs[0]]}),/duplicate/);assert.equal(store.jobs().length,1);}));
test('migration excludes sample jobs and never imports legacy submitted status as real',()=>withStore(async store=>{await store.migrate({profile:{...profile,email:'legacy@example.com'},jobs:[{id:'job-1',...job},{id:'job-99',...job,status:'submitted'}]});assert.equal(store.jobs().length,1);assert.equal(store.jobs()[0].status,'saved');assert.equal(store.jobs()[0].evidence,null);assert(!store.getSetting('profile').email.includes('legacy@example.com'));}));
test('local API enforces origin, authentication, static allowlist and durable CRUD',async()=>{const directory=await mkdtemp(path.join(os.tmpdir(),'jobpilot-api-'));const {server,store}=await createApp({directory,seed:false,importer:async()=>({...job,source:'test fixture'})});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;const headers={'X-JobPilot':'1','Content-Type':'application/json'};try{
  assert.equal((await fetch(base+'/api/state')).status,403);
  assert.equal((await fetch(base+'/api/state',{headers:{...headers,Origin:'https://evil.example'}})).status,403);
  assert.equal((await fetch(base+'/data/jobpilot.sqlite')).status,404);
  assert.equal((await fetch(base+'/server.mjs')).status,404);
  const created=await fetch(base+'/api/jobs',{method:'POST',headers,body:JSON.stringify(job)});assert.equal(created.status,201);const saved=await created.json();
  assert.equal((await fetch(base+'/api/jobs',{method:'POST',headers,body:JSON.stringify(job)})).status,409);
  assert.equal((await fetch(base+`/api/jobs/${saved.id}/prepare`,{method:'POST',headers,body:'{}'})).status,422);
  assert.equal((await fetch(base+'/api/state',{headers:{Origin:'chrome-extension://'+'a'.repeat(32),Authorization:'Bearer wrong'}})).status,401);
  const preflight=await fetch(base+'/api/state',{method:'OPTIONS',headers:{Origin:'chrome-extension://'+'a'.repeat(32),'Access-Control-Request-Headers':'X-JobPilot-Version'}});assert.match(preflight.headers.get('access-control-allow-headers'),/X-JobPilot-Version/);
  const token=store.getSetting('token');const response=await fetch(base+'/api/state',{headers:{Origin:'chrome-extension://'+'a'.repeat(32),Authorization:`Bearer ${token}`,'X-JobPilot-Version':'2.3.0'}});assert.equal(response.status,200);assert.equal((await response.json()).jobs.length,1);const companion=await(await fetch(base+'/api/companion',{headers})).json();assert.equal(companion.lastConnection.version,'2.3.0');assert(companion.lastConnection.lastSeenAt);
  assert.equal((await fetch(base+'/api/connection',{headers:{Authorization:`Bearer ${token}`}})).status,403);
  assert.equal((await fetch(base+'/api/jobs',{method:'POST',headers,body:'not-json'})).status,400);
}finally{await new Promise(resolve=>server.close(resolve));store.close();await rm(directory,{recursive:true,force:true});}});

test('a fresh checkout starts with no bundled resume or personal profile',async()=>{const directory=await mkdtemp(path.join(os.tmpdir(),'jobpilot-clean-start-'));const {server,store}=await createApp({directory});try{assert.equal(store.state().profile.name,'');assert.equal(store.state().profile.email,'');assert.equal(store.state().resume,null);assert.equal(store.jobs().length,0);}finally{server.close();store.close();await rm(directory,{recursive:true,force:true});}});
