import {browserFetch} from './lib/browser-api.mjs';
import { profileReadiness } from './extension/context.js';
import { createTailorUI } from './tailor-ui.js';
import { createWatchUI } from './watch-ui.js';
import { initCursor } from './cursor.js';
initCursor();
const $ = id => document.getElementById(id);
const escape = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[char]);
const labels = { saved:'Saved', prepared:'Draft ready', in_progress:'In progress', submitted:'Applied', interview:'Interview', offer:'Offer', rejected:'Not selected', archived:'Archived' };
let state = {profile:{}, jobs:[], events:[]};
let currentView = 'watch'; let selectedId; let toastTimer; let previousFocus; let busy = false;
async function api(route, data, method) {
  const response = await browserFetch(`/api${route}`, {method:method || (data ? 'POST' : 'GET'),headers:{'X-JobPilot':'1',...(data ? {'Content-Type':'application/json'} : {})}, ...(data ? {body:JSON.stringify(data)} : {})});
  const result = await response.json(); if (!response.ok) throw new Error(result.error || 'The request failed.'); return result;
}
function notify(message) { $('toast').textContent = message; $('toast').classList.add('is-visible'); clearTimeout(toastTimer); toastTimer = setTimeout(() => $('toast').classList.remove('is-visible'),5000); }
function failure(error) { notify(error.message || 'Something went wrong. Please try again.'); }
async function refresh() { state = await api('/state'); $('connection-state').textContent = 'Saved in this browser'; $('error-banner').hidden = true; render(); const companion=await api('/companion'); $('companion-connection').textContent=companion.lastConnection?`Last connected: ${time(companion.lastConnection.lastSeenAt)} · v${companion.lastConnection.version}. Open the extension on an application page to reconnect.`:'No companion connection recorded yet. Follow the steps below to pair it.'; }
function date(value) { return value ? new Date(value).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}) : '—'; }
function time(value) { return new Date(value).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}); }
function empty(title,copy) { return `<div class="empty-state"><strong>${title}</strong><p>${copy}</p></div>`; }
function row(job) { const analysis = job.analysis; return `<article class="job-row"><div class="job-main"><div class="job-title-line"><strong class="job-title">${escape(job.title)}</strong><span class="status-pill status-${job.status}">${labels[job.status]}</span></div><div class="job-company">${escape(job.company)}</div><div class="job-meta"><span>${escape(job.location || 'Location not listed')}</span>${job.followUp ? `<span>Follow up ${date(job.followUp+'T12:00:00')}</span>`:''}</div></div><div class="job-actions"><span class="job-score">${analysis?.mentioned.length ? `${analysis.matched.length}/${analysis.mentioned.length} skills overlap`:'Not scored'}</span><button class="job-action" data-action="open-job" data-id="${job.id}">Open →</button></div></article>`; }
function render() {
  const active = state.jobs.filter(j => !['archived','rejected','offer'].includes(j.status));
  $('queue-count').textContent = active.length;
  const start = new Date(); start.setHours(0,0,0,0); start.setDate(start.getDate()-6);
  const submitted = state.jobs.filter(j => j.evidence && new Date(j.submittedAt)>=start).length;
  $('stats-grid').innerHTML = `<div class="stat-card accent-stat"><strong>${active.filter(j => ['saved','prepared','in_progress'].includes(j.status)).length}</strong><span>In your pipeline</span></div><div class="stat-card"><strong>${submitted}</strong><span>Applied · last 7 days</span></div><div class="stat-card"><strong>${state.jobs.filter(j => j.status==='interview').length}</strong><span>Interviews</span></div>`;
  const upcoming = active.filter(j => ['saved','prepared','in_progress'].includes(j.status)).sort((a,b) => (b.analysis?.coverage || 0)-(a.analysis?.coverage || 0));
  $('dashboard-queue').innerHTML = upcoming.length ? upcoming.slice(0,5).map(row).join('') : empty('Your next role is out there.','Use Find jobs to discover openings and save the ones you like.');
  $('activity-list').innerHTML = state.events.length ? state.events.slice(0,5).map(event=>`<div class="activity-item"><div><p>${escape(event.message)}</p><time>${time(event.at)}</time></div></div>`).join('') : '<p class="quiet">Your progress will appear here.</p>';
  const followups = active.filter(j=>j.followUp).sort((a,b)=>a.followUp.localeCompare(b.followUp)).slice(0,4);
  $('followups').innerHTML = followups.length ? followups.map(j=>`<button class="followup-row" data-action="open-job" data-id="${j.id}"><strong>${escape(j.company)}</strong><span>${date(j.followUp+'T12:00:00')}</span></button>`).join('') : '<p class="quiet">Set a follow-up date inside an application. We’ll keep it here.</p>';
  const missing = profileReadiness(state).length || !state.profile.resumeText;
  $('setup-note').hidden = !missing;
  $('setup-note').innerHTML = '<strong>One small thing before you start.</strong> Add your contact details and résumé in <button class="text-button" data-nav="profile">Your profile →</button>';
  $('profile-name').textContent = state.profile.name?.split(' ').slice(0,2).join(' ') || 'Your profile';
  $('avatar-initials').textContent = (state.profile.name || 'Job Pilot').split(' ').slice(0,2).map(word=>word[0]).join('');
  $('resume-name').textContent = state.resume ? `${state.resume.name} · ${Math.round(state.resume.bytes/1024)} KB` : 'No résumé uploaded';
  if (currentView !== 'profile') fillProfile();
  renderQueue(); if (currentView === 'detail') renderDetail(); if (currentView === 'watch') watch.syncSaved();
}
function fillProfile() { for (const [key,value] of Object.entries(state.profile)) { const field = $('profile-form').elements.namedItem(key); if (field) field.value=value; } }
function renderQueue() { const query=$('job-search').value.trim().toLowerCase(); const filter=$('status-filter').value; const jobs=state.jobs.filter(job => (filter==='all' || (filter==='active' ? !['archived','rejected','offer'].includes(job.status) : job.status===filter)) && `${job.title} ${job.company} ${job.location} ${job.description}`.toLowerCase().includes(query)); $('toolbar-result').textContent=`${jobs.length} roles`; $('full-queue').innerHTML=jobs.length?jobs.map(row).join(''):empty('No roles here yet.','Import a listing, or try another filter.'); }
function setView(view) { if(view==='discover'||view==='jobs')view='watch'; currentView=view; $('workspace-context').textContent=({watch:'Find jobs',queue:'My applications',tailor:'Tailor résumé',profile:'Your profile',dashboard:'My progress',settings:'Tools & backups',detail:'Application workspace'})[view]; document.querySelectorAll('dialog[open]').forEach(dialog=>dialog.close()); document.querySelectorAll('[data-view]').forEach(section=>{ section.hidden=section.dataset.view!==view; section.classList.toggle('is-visible',!section.hidden); }); document.querySelectorAll('[data-nav]').forEach(button=>{const active=button.dataset.nav===view;button.classList.toggle('is-active',active); if(active)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current');}); $('sidebar').classList.remove('is-open'); document.querySelector('.nav-more').open=false; $('mobile-menu').setAttribute('aria-expanded','false'); if(view==='profile')fillProfile(); if(view==='detail')renderDetail(); if(view==='tailor')tailor.enter().catch(failure); if(view==='watch')watch.enter().catch(failure); window.scrollTo({top:0,behavior:'instant'}); }
function renderDetail() {
  const job=state.jobs.find(j=>j.id===selectedId); if(!job){setView('queue');return;}
  const a=job.analysis; const p=job.preparation; const canPrepare=!['submitted','interview','offer','rejected','archived'].includes(job.status);
  $('detail-content').innerHTML=`<button class="text-button back-button" data-nav="queue">← All applications</button><div class="page-heading heading-with-actions"><div><p class="eyebrow">${escape(job.company)}</p><h1 class="detail-title">${escape(job.title)}</h1><p class="lede">${escape(job.location || 'Location not listed')} ${job.salary?'· '+escape(job.salary):''}</p></div><div class="heading-actions"><a class="button button-secondary" href="${escape(job.url)}" target="_blank" rel="noopener noreferrer">Open listing ↗</a><button class="button button-secondary" data-action="edit-job" data-id="${job.id}">Edit details</button></div></div>
  <div class="workspace-grid"><div><section class="panel workspace-panel"><div class="panel-heading"><h2>Application draft</h2><span class="status-pill status-${job.status}">${labels[job.status]}</span></div>${p?`<label class="draft-label">Your introduction<textarea id="draft-text" rows="13" maxlength="10000">${escape(p.opening)}</textarea></label><div class="stack-actions horizontal"><button class="button button-primary" data-action="save-draft" data-id="${job.id}">Save draft</button><button class="button button-secondary" data-action="copy-draft">Copy</button><button class="button button-secondary" data-action="download-packet" data-id="${job.id}">Download application pack</button></div><p class="field-help">This draft uses your supplied résumé. Edit it in your own voice, then save it before using the extension.</p>`:`<p class="quiet">Create a short introduction from the skills actually present in your résumé.</p>${a.blockers.length?`<ul class="blockers">${a.blockers.map(item=>`<li>${escape(item)}</li>`).join('')}</ul>`:''}${canPrepare?`<button class="button button-primary" data-action="prepare" data-id="${job.id}">Prepare application →</button>`:''}`}</section>
  <section class="panel workspace-panel"><h2>The job description</h2><p class="job-description">${escape(job.description)}</p></section></div>
  <div><section class="panel workspace-panel"><p class="eyebrow">A TRANSPARENT COMPARISON</p><h2>${a.coverage===null?'No recognised skills':`${a.matched.length} of ${a.mentioned.length} skills overlap`}</h2><p class="quiet">${escape(a.method)}</p><h3>Found in your résumé</h3><div class="skill-tags">${a.matched.map(skill=>`<span class="skill-tag">${escape(skill)}</span>`).join('')||'<span class="quiet">No keyword overlap found.</span>'}</div><h3>Not found in your résumé</h3><div class="skill-tags missing-skills">${a.missing.map(skill=>`<span class="skill-tag">${escape(skill)}</span>`).join('')||'<span class="quiet">No gaps among recognised keywords.</span>'}</div><p class="field-help">This is a keyword check, not a full requirements assessment. Review qualifications, location, and eligibility in the listing.</p></section>
  <section class="panel workspace-panel"><h2>The next step</h2>${job.submissionAttempt?.state==='pending'&&!job.evidence?`<div class="confirmation"><strong>Submission needs verification</strong><p>A submission was attempted. Check the employer page or email before trying again.</p><button class="button button-secondary" data-action="clear-attempt" data-id="${job.id}">I verified it was not sent</button></div>`:''}${job.evidence?`<div class="confirmation"><strong>Application recorded · ${date(job.submittedAt)}</strong><p>${escape(job.evidence.note)}</p><span class="field-help">${job.evidence.source==='browser_confirmation'?'Detected by the browser companion':'Confirmed by you'} on ${date(job.evidence.recordedAt)}.</span></div><label class="draft-label">Outcome<select id="outcome-status">${['submitted','interview','offer','rejected','archived'].map(s=>`<option value="${s}" ${s===job.status?'selected':''}>${labels[s]}</option>`).join('')}</select></label><button class="button button-secondary" data-action="outcome" data-id="${job.id}">Save outcome</button>`:`<p class="quiet">Open the listing’s application form in Chrome or Edge. In the JobPilot companion, select this prepared role, review the saved details, and choose Auto-apply this role. It pauses for missing answers and records detected confirmations.</p><button class="button button-primary" data-action="confirm-application" data-id="${job.id}">Record application confirmation</button><button class="text-button" data-nav="settings">Set up browser autofill ↗</button>`}</section>
  <section class="panel workspace-panel"><h2>Notes & follow-up</h2><form id="notes-form" data-id="${job.id}"><label class="draft-label">Follow-up date<input type="date" name="followUp" value="${escape(job.followUp)}"></label><label class="draft-label">Your notes<textarea name="notes" rows="5" maxlength="10000">${escape(job.notes)}</textarea></label><button class="button button-secondary" type="submit">Save notes</button></form><button class="text-button archive-button" data-action="archive" data-id="${job.id}">${job.status==='archived'?'Archived':'Archive role'}</button></section></div></div>`;
}
function openModal(content) { previousFocus=document.activeElement; $('modal-content').innerHTML=content; $('modal-backdrop').hidden=false; document.body.classList.add('modal-open'); ($('modal-content').querySelector('input,textarea,button')||$('modal-close')).focus(); }
function closeModal() { $('modal-backdrop').hidden=true; document.body.classList.remove('modal-open'); previousFocus?.focus(); }
function openImport(job={}) { openModal(`<p class="eyebrow">${job.id?'REFINE THE DETAILS':'A NEW OPPORTUNITY'}</p><h2 id="modal-title">${job.id?'Edit this role.':'Bring a role into focus.'}</h2><p class="modal-subtitle">Paste a specific job link to import it, or enter the details below. Greenhouse, Lever, and pages with structured job data are supported.</p><form id="job-form" data-id="${job.id||''}" class="modal-form"><label>Listing URL<input name="url" type="url" value="${escape(job.url)}" required placeholder="https://…"></label>${job.id?'':'<button class="button button-secondary" type="button" data-action="import-url">Import details from URL</button>'}<p id="import-message" class="field-help" role="status"></p><div class="form-grid"><label>Role title<input name="title" required maxlength="300" value="${escape(job.title)}"></label><label>Company<input name="company" required maxlength="200" value="${escape(job.company)}"></label><label>Location<input name="location" maxlength="300" value="${escape(job.location)}"></label><label>Salary, if listed<input name="salary" maxlength="300" value="${escape(job.salary)}"></label></div><label>Full job description<textarea name="description" rows="9" required maxlength="100000" placeholder="Paste the description if the website blocks imports.">${escape(job.description)}</textarea></label><div class="modal-actions"><button type="button" class="button button-secondary" data-action="close-modal">Cancel</button><button class="button button-primary" type="submit">${job.id?'Save changes':'Add to applications'}</button></div></form>`); }
function download(name,content,type='application/json') { const url=URL.createObjectURL(new Blob([content],{type})); const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }
async function downloadResume() { const response=await browserFetch('/api/resume',{headers:{'X-JobPilot':'1'}}); if(!response.ok)throw new Error('Upload your résumé in Profile first.'); download(state.resume?.name||'Resume.pdf',await response.arrayBuffer(),'application/pdf'); }
async function runAction(button) {
  const action=button.dataset.action; const id=button.dataset.id;
  if(action==='add-job')return openImport();
  if(action==='open-job'){selectedId=id;return setView('detail');}
  if(action==='edit-job')return openImport(state.jobs.find(j=>j.id===id));
  if(action==='close-modal')return closeModal();
  if(action==='import-url'){const form=$('job-form'); $('import-message').textContent='Reading the job posting…';try{const imported=await api('/import',{url:form.elements.url.value}); for(const key of ['title','company','location','salary','description']) form.elements[key].value=imported[key]||''; $('import-message').textContent=`Imported from ${imported.source}. Review the details before saving.`;}catch(error){$('import-message').textContent=error.message;}return;}
  if(action==='prepare'){await api(`/jobs/${id}/prepare`,{}); await refresh();notify('Your application draft is ready.');return;}
  if(action==='prepare-all'){const saved=state.jobs.filter(j=>j.status==='saved');if(!saved.length)return notify('There are no saved roles waiting for preparation.'); let count=0;const failed=[];for(const job of saved){try{await api(`/jobs/${job.id}/prepare`,{});count++;}catch(error){failed.push(`${job.company}: ${error.message}`);}}await refresh(); if(failed.length)openModal(`<h2 id="modal-title">${count} drafts prepared</h2><p class="quiet">These roles need attention:</p><ul>${failed.map(message=>`<li>${escape(message)}</li>`).join('')}</ul>`);else notify(`${count} drafts prepared.`);return;}
  if(action==='save-draft'){await api(`/jobs/${id}/draft`,{opening:$('draft-text').value});await refresh();notify('Draft saved.');return;}
  if(action==='copy-draft'){await navigator.clipboard.writeText($('draft-text').value);return notify('Draft copied.');}
  if(action==='download-packet'){const job=state.jobs.find(j=>j.id===id);const packet=[`${job.title} — ${job.company}`,job.url,`Prepared: ${date(job.preparation.generatedAt)}`,'', 'INTRODUCTION', $('draft-text').value,'','CONTACT DETAILS',state.profile.name,state.profile.email,state.profile.phone,state.profile.portfolio,state.profile.github,state.profile.linkedin,'','SKILLS IN COMMON',job.analysis.matched.join(', '),'','NOT FOUND IN RÉSUMÉ',job.analysis.missing.join(', '),'','JOB DESCRIPTION',job.description].join('\n');download(`${job.company.replace(/[^\w-]/g,'_')}-application.txt`,packet,'text/plain');return;}
  if(action==='confirm-application'){const job=state.jobs.find(j=>j.id===id);return openModal(`<p class="eyebrow">AFTER YOU HAVE APPLIED</p><h2 id="modal-title">Record the confirmation.</h2><p class="modal-subtitle">This records a completed application to ${escape(job.company)}. It does not submit a form.</p><form id="confirmation-form" data-id="${id}" class="modal-form"><label>Confirmation message, reference, or your note<textarea name="note" rows="5" minlength="12" maxlength="3000" required placeholder="For example: Received the application confirmation email, reference…"></textarea></label><label>Confirmation page URL (optional)<input name="url" type="url"></label><label class="checkbox-label"><input type="checkbox" required> I completed the submission on the employer’s website.</label><button class="button button-primary">Record completed application</button></form>`);}
  if(action==='clear-attempt'){const job=state.jobs.find(j=>j.id===id);if(!window.confirm('Only continue if you checked the employer page and confirmation email and verified that this application was NOT submitted. Allow another attempt?'))return;await api(`/jobs/${id}/attempt`,{action:'not-sent',attemptId:job.submissionAttempt.id,confirmedNotSent:true});await refresh();notify('The previous attempt was marked not sent.');return;}
  if(action==='outcome'){await api(`/jobs/${id}/status`,{status:$('outcome-status').value});await refresh();return notify('Outcome saved.');}
  if(action==='archive'){const job=state.jobs.find(j=>j.id===id);if(job.status==='archived')return;await api(`/jobs/${id}/status`,{status:'archived'});await refresh();return notify('Role archived. It remains available in All statuses.');}
  if(action==='export'){const backup=await api('/backup');download(`jobpilot-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(backup,null,2));return;}
  if(action==='disk-backup'){await api('/backup',{});return notify('Recovery snapshot saved on this computer.');}
  if(action==='copy-pairing'){const connection=await api('/connection');await navigator.clipboard.writeText(connection.token);return notify('Pairing key copied. Paste it into the JobPilot extension.');}
  if(action==='download-resume')return downloadResume();
  if(action==='legacy-export'){const old=localStorage.getItem('jobpilot-local-v1');if(!old)return notify('No older JobPilot data was found in this browser.');download('jobpilot-legacy-data.json',old);}
}
document.addEventListener('click',async event=>{const button=event.target.closest('[data-action],[data-nav]');if(!button)return;event.preventDefault();if(button.dataset.nav){setView(button.dataset.nav);return;}if(busy)return;busy=true;button.disabled=true;try{await runAction(button);}catch(error){failure(error);}finally{busy=false;button.disabled=false;}});
document.addEventListener('submit',async event=>{if(['discovery-form','company-form','tailor-form','watch-filter-form','watch-request-form'].includes(event.target.id))return;event.preventDefault();if(busy)return;busy=true;const form=event.target;const button=form.querySelector('[type="submit"],button:not([type])');if(button)button.disabled=true;try{const data=Object.fromEntries(new FormData(form));if(form.id==='profile-form'){await api('/profile',data);await refresh();fillProfile();$('profile-saved').textContent='Saved just now';notify('Profile saved on this computer.');}if(form.id==='job-form'){const id=form.dataset.id;const job=await api(id?`/jobs/${id}`:'/jobs',data,id?'PATCH':'POST');closeModal();await refresh();selectedId=job.id;setView('detail');notify(id?'Role updated.':'Role added.');}if(form.id==='notes-form'){await api(`/jobs/${form.dataset.id}`,data,'PATCH');await refresh();notify('Notes saved.');}if(form.id==='confirmation-form'){await api(`/jobs/${form.dataset.id}/status`,{status:'submitted',evidence:data});closeModal();await refresh();notify('Application confirmation recorded.');}}catch(error){failure(error);}finally{busy=false;if(button)button.disabled=false;}});
$('job-search').addEventListener('input',renderQueue);$('status-filter').addEventListener('change',renderQueue);
$('modal-close').addEventListener('click',closeModal);$('modal-backdrop').addEventListener('click',event=>{if(event.target===$('modal-backdrop'))closeModal();});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!document.querySelector('dialog[open]')){closeModal();$('sidebar').classList.remove('is-open');$('mobile-menu').setAttribute('aria-expanded','false');}if(event.key==='Tab'&&!$('modal-backdrop').hidden){const controls=[...$('modal').querySelectorAll('button,input,textarea,select,a[href]')].filter(el=>!el.disabled&&el.getClientRects().length);const first=controls[0],last=controls.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}});
$('mobile-menu').addEventListener('click',()=>{$('mobile-menu').setAttribute('aria-expanded',String($('sidebar').classList.toggle('is-open')));});
function theme(value){const next=['burgundy','forest','beige','neon','azure','coral','amber'].includes(value)?value:'burgundy';document.documentElement.dataset.theme=next;$('theme-select').value=next;try{localStorage.setItem('jobpilot-theme-v4',next);}catch{}}
$('theme-select').addEventListener('change',event=>theme(event.target.value));try{const previous=localStorage.getItem('jobpilot-theme-v3')||localStorage.getItem('jobpilot-theme-v2');theme(localStorage.getItem('jobpilot-theme-v4')||(previous&&!['beige','forest'].includes(previous)?previous:'burgundy'));}catch{theme('burgundy');}
$('resume-upload').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;if(file.size>8_000_000){notify('Choose a PDF smaller than 8 MB.');event.target.value='';return;}try{notify('Reading your résumé locally…');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);const result=await api('/resume',{name:file.name,base64:btoa(binary)});await refresh();fillProfile();notify(result.warning||'Résumé uploaded. Review the extracted text, then save your profile.');}catch(error){failure(error);}finally{event.target.value='';}});
$('restore-upload').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>16_000_000)throw new Error('This backup exceeds 16 MB.');const data=JSON.parse(await file.text());if(!window.confirm('Restore this backup? Current data will be saved in a recovery snapshot before replacement.'))return;await api('/restore',data);await refresh();notify('Backup restored.');}catch(error){failure(error);}finally{event.target.value='';}});
const tailor=createTailorUI({api,getState:()=>state,notify});
const watch=createWatchUI({notify,getSavedJobs:()=>state.jobs,getLegacyCompanies:()=>api('/discover/sources'),saveJob:async job=>{await api('/watch/save',job);await refresh();notify('Role saved in Applications on this browser.');}});
try{await refresh();if(!state.migrated){let old;try{old=JSON.parse(localStorage.getItem('jobpilot-local-v1')||'null');}catch{}if(old){await api('/migrate',old);await refresh();}}setView(['watch','jobs','dashboard','discover','queue','tailor','profile','settings'].includes(location.hash.slice(1))?location.hash.slice(1):'watch');}catch(error){$('connection-state').textContent='Browser storage unavailable';$('error-banner').hidden=false;$('error-banner').textContent='JobPilot could not open browser storage. Allow site storage and reload to use the résumé workspace. Company browsing remains available.';setView('watch');}
window.addEventListener('focus',()=>{if(currentView!=='profile'&&currentView!=='detail'&&$('modal-backdrop').hidden)refresh().catch(()=>{});});

window.addEventListener('hashchange',()=>{const view=location.hash.slice(1);if(['watch','jobs','dashboard','discover','queue','tailor','profile','settings'].includes(view))setView(view);});

for(const element of document.querySelectorAll('[data-site-address]'))element.textContent=location.origin;
